"""Pydantic schemas for RecoverAI Agent."""

from enum import Enum
from typing import List, Literal, Optional
from pydantic import BaseModel, Field, field_validator


class RecoveryAction(str, Enum):
    RETRY_PAYMENT = "RETRY_PAYMENT"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    SEND_REMINDER = "SEND_REMINDER"
    SUGGEST_ALTERNATE_PAYMENT_METHOD = "SUGGEST_ALTERNATE_PAYMENT_METHOD"
    ESCALATE_TO_MERCHANT = "ESCALATE_TO_MERCHANT"
    STOP_RECOVERY = "STOP_RECOVERY"


class CaseStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RECOVERED = "RECOVERED"
    STOPPED = "STOPPED"
    ESCALATED = "ESCALATED"


class RecoveryRecommendation(BaseModel):
    """Structured, validated recommendation generated by the AI Recovery Agent."""

    risk_score: int = Field(ge=0, le=100, description="Risk of permanent revenue loss from 0 to 100")
    recovery_probability: float = Field(ge=0.0, le=1.0, description="Estimated probability of successful recovery")
    recommended_action: RecoveryAction = Field(description="The next best recovery action chosen by the AI")
    priority: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(default="MEDIUM", description="Urgency of intervention")
    retry_after_minutes: Optional[int] = Field(default=None, ge=1, le=10080, description="Scheduled delay in minutes if retrying")
    reason: str = Field(max_length=2000, description="Detailed human-readable explanation of why this action was chosen")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in this recommendation")
    provider_used: str = Field(default="demo", description="Which AI provider emitted this recommendation ('gemini', 'demo', 'gemini-fallback')")

    @field_validator("priority", mode="before")
    @classmethod
    def normalize_priority(cls, v):
        if isinstance(v, str):
            v_upper = v.upper().strip()
            if v_upper in {"LOW", "MEDIUM", "HIGH", "CRITICAL"}:
                return v_upper
        return "MEDIUM"

    @classmethod
    def from_dict(cls, payload: dict) -> "RecoveryRecommendation":
        """Factory method for backwards compatibility with dictionary payloads."""
        if not isinstance(payload, dict):
            raise ValueError("Payload must be a dictionary")
        # Ensure action is string or enum
        action_val = payload.get("recommended_action")
        if isinstance(action_val, RecoveryAction):
            action_str = action_val.value
        else:
            action_str = str(action_val) if action_val else ""

        if action_str not in {a.value for a in RecoveryAction}:
            raise ValueError(f"Unsupported recovery action: {action_str}")

        return cls(
            risk_score=int(payload.get("risk_score", 50)),
            recovery_probability=float(payload.get("recovery_probability", 0.5)),
            recommended_action=RecoveryAction(action_str),
            priority=payload.get("priority", "MEDIUM"),
            retry_after_minutes=payload.get("retry_after_minutes"),
            reason=str(payload.get("reason", "No reason provided")),
            confidence=float(payload.get("confidence", 0.8)),
            provider_used=str(payload.get("provider_used", "demo")),
        )

    def to_dict(self) -> dict:
        """Serialize for JSON responses and database audit logging."""
        return {
            "risk_score": self.risk_score,
            "recovery_probability": round(self.recovery_probability, 2),
            "recommended_action": self.recommended_action.value,
            "priority": self.priority,
            "retry_after_minutes": self.retry_after_minutes,
            "reason": self.reason,
            "confidence": round(self.confidence, 2),
            "provider_used": self.provider_used,
        }
